name: ci

on:
  push
  #pull_request:
  #  branches: ["develop"]

jobs:

  build:

    env:
      Configuration: Release
      DotNetVersion: 6.0.x

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DotNetVersion }}

      - name: Install Codecov
        run: 'dotnet tool install -g codecov.tool'
        
      - name: Build
        run: 'dotnet build -c $env:Configuration'

      
      - name: Test
        run: 'dotnet test -c ${{ env.Configuration }} /p:CollectCoverage=true /p:CoverletOutputFormat=OpenCover /p:CoverletOutput=./Coverage.xml'


      - name: Publish Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./Coverage.xml


      #- name: Publish Coverage
      #  run: 'codecov -f test\ReportPortal.Client.IntegrationTests\Coverage.*.xml'

      


  